# Generated by Django 5.1.4 on 2024-12-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('ebayCondition', models.CharField(max_length=20)),
                ('tagWidth', models.IntegerField()),
                ('tagLength', models.IntegerField()),
                ('insideLeg', models.IntegerField()),
                ('hem', models.IntegerField()),
                ('outsideLeg', models.IntegerField()),
                ('rise', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('condition1', models.CharField(max_length=250)),
                ('condition2', models.CharField(max_length=250)),
                ('condition3', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=25)),
                ('colour', models.CharField(max_length=10)),
                ('insideLegMeasured', models.CharField(max_length=20)),
                ('sizeType', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('closure', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('exactMaterial', models.CharField(max_length=120)),
                ('feature', models.CharField(max_length=15)),
                ('fabricWash', models.CharField(max_length=60)),
                ('fit', models.CharField(max_length=10)),
                ('garmentCare', models.CharField(max_length=30)),
                ('legStyle', models.CharField(max_length=15)),
                ('occasion', models.CharField(max_length=15)),
                ('size', models.IntegerField()),
                ('tagSize', models.CharField(max_length=15)),
                ('measuredSize', models.CharField(max_length=25)),
                ('notes', models.CharField(max_length=35)),
                ('waistCirc', models.CharField(max_length=6)),
                ('riseIS', models.CharField(max_length=200)),
                ('womenUKSize', models.CharField(max_length=15)),
                ('inseam', models.CharField(max_length=6)),
                ('riseInches', models.CharField(max_length=2000)),
                ('paths', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.CharField(default='Not Specified', max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32)),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('views', models.IntegerField()),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
